name = "project1"
main = "src/worker.js"
compatibility_date = "2023-06-10"

kv_namespaces = [
   { binding = "TEST", id = "e2d144caa0ff42f0b99b67e2436f7d20",preview_id = "827dbbdaa3a24de38822e60c6f377b10"  }
]